Repository bitcoin-s/bitcoin-s-ts, pull requests merged in 2022-02, with the labels that each got.

#73 Add axis labels to charts
  wallet-server-ui/src/app/component/accept-offer/accept-offer.component.ts
  wallet-server-ui/src/app/component/contract-detail/contract-detail.component.ts
  wallet-server-ui/src/app/component/new-offer/new-offer.component.ts
Labels: enhancement, wallet

#74 Bump docker publish timeout to 90 minutes
  .github/workflows/docker-publish.yml
Labels: ci, docker

#75 Darkmode service, chart service, darkmode charts
  wallet-server-ui/src/app/app.component.html
  wallet-server-ui/src/app/app.component.ts
  wallet-server-ui/src/app/component/accept-offer/accept-offer.component.html
  wallet-server-ui/src/app/component/accept-offer/accept-offer.component.ts
  wallet-server-ui/src/app/component/contract-detail/contract-detail.component.html
  wallet-server-ui/src/app/component/contract-detail/contract-detail.component.ts
  wallet-server-ui/src/app/component/new-offer/new-offer.component.html
  wallet-server-ui/src/app/component/new-offer/new-offer.component.ts
  wallet-server-ui/src/app/configuration/configuration.component.ts
  wallet-server-ui/src/assets/i18n/en.json
  wallet-server-ui/src/service/auth.service.ts
  wallet-server-ui/src/service/chart.service.ts
  wallet-server-ui/src/service/dark-mode.service.ts
  wallet-server-ui/src/service/wallet-state-service.ts
Labels: enhancement

#79 Expose ignoreCreationTime flag for rescan
  wallet-server-ui/src/app/component/debug/debug.component.html
  wallet-server-ui/src/app/component/debug/debug.component.scss
  wallet-server-ui/src/app/component/debug/debug.component.ts
  wallet-server-ui/src/assets/i18n/en.json
Labels: enhancement, wallet

#81 Set loading flag during create announcement
  oracle-server-ui/src/app/new-announcement/new-announcement.component.ts
Labels: bug, oracle

#80 Support ranged outcome values
  wallet-server-ui/src/app/component/contract-detail/contract-detail.component.ts
  wallet-server-ui/src/service/chart.service.ts
  wallet-server-ui/src/util/utils.ts
Labels: enhancement, wallet

#82 Add telegram to About pages
  oracle-server-ui/src/app/about/about.component.html
  oracle-server-ui/src/assets/i18n/en.json
  wallet-server-ui/src/app/component/about/about.component.html
Labels: documentation

#83 Shorten logout timer by a fudge factor to avoid 400 errors near logout
  wallet-server-ui/src/service/auth.service.ts
Labels: bug, wallet

#85 Add top level README
  README.md
Labels: documentation

#84 Version 1.9.0, build version, new DLCStates, spinners
  common-ts/package-lock.json
  oracle-server-ui-proxy/build/buildVersion.js
  oracle-server-ui-proxy/package-lock.json
  oracle-server-ui/package-lock.json
  oracle-server-ui/src/app/about/about.component.html
  oracle-server-ui/src/type/proxy-server-types.ts
  wallet-server-ui-proxy/build/buildVersion.js
  wallet-server-ui-proxy/package-lock.json
  wallet-server-ui/package-lock.json
  wallet-server-ui/src/app/component/about/about.component.html
  wallet-server-ui/src/app/component/accept-offer/accept-offer.component.ts
  wallet-server-ui/src/app/component/contract-detail/contract-detail.component.html
  wallet-server-ui/src/app/component/contract-detail/contract-detail.component.scss
  wallet-server-ui/src/app/component/contract-detail/contract-detail.component.ts
  wallet-server-ui/src/service/auth.service.ts
  wallet-server-ui/src/service/websocket.service.ts
  wallet-server-ui/src/type/proxy-server-types.ts
  wallet-server-ui/src/type/wallet-server-types.ts
  wallet-server-ui/src/util/utils.ts
  wallet-ts/lib/type/wallet-types.ts
  wallet-ts/package-lock.json
Labels: enhancement, dependencies, wallet, oracle

#89 Download log files
  common-ts/lib/util/server-util.ts
  oracle-server-ui-proxy/config.json
  oracle-server-ui-proxy/middleware/download.ts
  oracle-server-ui-proxy/routes/proxy.ts
  oracle-server-ui-proxy/server.ts
  oracle-server-ui-proxy/type/run-config.ts
  oracle-server-ui-proxy/type/server-config.ts
  oracle-server-ui/src/app/component/advanced/advanced.component.html
  oracle-server-ui/src/app/component/advanced/advanced.component.scss
  oracle-server-ui/src/app/component/advanced/advanced.component.ts
  oracle-server-ui/src/assets/i18n/en.json
  oracle-server-ui/src/service/auth.service.ts
  oracle-server-ui/src/service/message.service.ts
  wallet-server-ui-proxy/config.json
  wallet-server-ui-proxy/middleware/backup.ts
  wallet-server-ui-proxy/middleware/download.ts
  wallet-server-ui-proxy/routes/proxy.ts
  wallet-server-ui-proxy/server.ts
  wallet-server-ui-proxy/type/run-config.ts
  wallet-server-ui-proxy/type/server-config.ts
  wallet-server-ui/src/app/component/debug/debug.component.html
  wallet-server-ui/src/app/component/debug/debug.component.ts
  wallet-server-ui/src/assets/i18n/en.json
  wallet-server-ui/src/service/message.service.ts
Labels: enhancement

#93 Implement publishing of the wallet-ts project
  .github/workflows/npm-publish.yml
Labels: build

#94 Remove private field on package.json so we can publish
  wallet-ts/package.json
Labels: build

#96 Add bitcoin-s organization to wallet-ts library
  wallet-ts/package.json
Labels: build

#97 Try to change access explicitly to public
  .github/workflows/npm-publish.yml
Labels: build

#92 Change BACKUP_PATH to BITCOIN_S_HOME
  oracle-server-ui-proxy/type/run-config.ts
  wallet-server-ui-proxy/type/run-config.ts
Labels: documentation, docker

#99 Add docker workflows for tagged releases
  .github/workflows/docker-publish.yml
Labels: docker, build

#100 Removes the 'v' prefix for detecting a tag
  .github/workflows/docker-publish.yml
Labels: docker, build

#102 Install wallet-server-ui dependencies ahead of build
  .github/workflows/Compile.yml
  wallet-server-ui/src/app/app.component.spec.ts
  wallet-server-ui/src/app/dialog/logout/logout.component.spec.ts
Labels: dependencies

#103 Angular 13 update
  oracle-server-ui-proxy/package-lock.json
  oracle-server-ui/package-lock.json
  oracle-server-ui/package.json
  oracle-server-ui/src/polyfills.ts
  oracle-server-ui/src/scss/material-theme.scss
  wallet-server-ui-proxy/config.json
  wallet-server-ui-proxy/package-lock.json
  wallet-server-ui/package-lock.json
  wallet-server-ui/package.json
  wallet-server-ui/proxy.conf.json
  wallet-server-ui/src/app/app.module.ts
  wallet-server-ui/src/environments/environment.prod.ts
  wallet-server-ui/src/environments/environment.ts
  wallet-server-ui/src/polyfills.ts
  wallet-server-ui/src/scss/material-theme.scss
  wallet-ts/package-lock.json
Labels: enhancement, build, dependencies

#106 Add repository tag to package.jsons
  common-ts/package.json
  oracle-server-ts/package.json
  oracle-server-ui-proxy/package.json
  oracle-server-ui/package.json
  wallet-server-ui-proxy/package.json
  wallet-server-ui/package.json
  wallet-ts/package.json
Labels: documentation, dependencies

#105 Add warning for enum contracts that don't pay you total collateral
  wallet-server-ui/src/app/component/new-offer/new-offer.component.html
  wallet-server-ui/src/app/component/new-offer/new-offer.component.ts
  wallet-server-ui/src/assets/i18n/en.json
Labels: enhancement

#108 Show Funded and Unfunded address lists on Wallet
  wallet-server-ui/src/app/component/wallet-balance/wallet-balance.component.html
  wallet-server-ui/src/app/component/wallet-balance/wallet-balance.component.scss
  wallet-server-ui/src/app/component/wallet-balance/wallet-balance.component.ts
  wallet-server-ui/src/assets/i18n/en.json
  wallet-server-ui/src/service/wallet-state-service.ts
Labels: enhancement

#107 Add QR Code scanning to Send Funds dialog
  wallet-server-ui/package-lock.json
  wallet-server-ui/package.json
  wallet-server-ui/src/app/app.module.ts
  wallet-server-ui/src/app/dialog/send-funds-dialog/send-funds-dialog.component.html
  wallet-server-ui/src/app/dialog/send-funds-dialog/send-funds-dialog.component.scss
  wallet-server-ui/src/app/dialog/send-funds-dialog/send-funds-dialog.component.ts
  wallet-server-ui/src/assets/i18n/en.json
Labels: enhancement

#110 Event id sorting
  wallet-server-ui/src/app/component/accept-offer/accept-offer.component.html
  wallet-server-ui/src/app/component/accept-offer/accept-offer.component.scss
  wallet-server-ui/src/app/component/accept-offer/accept-offer.component.ts
  wallet-server-ui/src/app/component/contracts/contracts.component.ts
  wallet-server-ui/src/app/component/new-offer/new-offer.component.html
  wallet-server-ui/src/app/component/new-offer/new-offer.component.scss
  wallet-server-ui/src/app/component/new-offer/new-offer.component.ts
  wallet-server-ui/src/app/dialog/send-funds-dialog/send-funds-dialog.component.html
  wallet-server-ui/src/app/dialog/send-funds-dialog/send-funds-dialog.component.scss
  wallet-server-ui/src/assets/i18n/en.json
  wallet-server-ui/src/service/auth.service.ts
  wallet-server-ui/src/service/wallet-state-service.ts
  wallet-server-ui/src/service/websocket.service.ts
  wallet-server-ui/src/styles.scss
  wallet-server-ui/src/util/utils.ts
  wallet-server-ui/src/util/validators.ts
Labels: bug, wallet

#111 Add trimOnPaste() and use across application
  wallet-server-ui/src/app/component/accept-offer/accept-offer.component.html
  wallet-server-ui/src/app/component/accept-offer/accept-offer.component.ts
  wallet-server-ui/src/app/component/build-accept-offer/build-accept-offer.component.html
  wallet-server-ui/src/app/component/build-accept-offer/build-accept-offer.component.ts
  wallet-server-ui/src/app/component/contract-detail/contract-detail.component.html
  wallet-server-ui/src/app/component/contract-detail/contract-detail.component.ts
  wallet-server-ui/src/app/component/new-offer/new-offer.component.html
  wallet-server-ui/src/app/component/new-offer/new-offer.component.ts
  wallet-server-ui/src/app/dialog/send-funds-dialog/send-funds-dialog.component.html
  wallet-server-ui/src/app/dialog/send-funds-dialog/send-funds-dialog.component.ts
  wallet-server-ui/src/util/utils.ts
Labels: enhancement, wallet
